### ISSUE TITLE
Error when run "npm run dev"

### ISSUE THREAD

**Issue by elfman** [topcoder-platform/community-app#20]
I just clone this repository and didn't modify any thing, when I run "npm run dev" in terminal, it shows errors. Here is the log.

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
/Users/luoxiongwen/Code/topcoder/community-app/node_modules/._tc-accounts@0.0.1@tc-accounts/exports.js:1
(function (exports, require, module, __filename, __dirname) { export { configureConnector, getFreshToken, logout } from './connector/connector-wrapper.js'
                                                               ^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:545:28)
    at Module._extensions..js (module.js:582:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/luoxiongwen/Code/topcoder/community-app/node_modules/._babel-register@6.24.1@babel-register/lib/node.js:152:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/luoxiongwen/Code/topcoder/community-app/src/shared/actions/auth.js:8:1)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! community-app@1.0.0 dev: `NODE_ENV=development node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the community-app@1.0.0 dev script 'NODE_ENV=development node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the community-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs community-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls community-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/luoxiongwen/Code/topcoder/community-app/npm-debug.log```

**Comment by birdofpreyru** [comment]
@elfman I'll look into this later. For now try a different commit. Most probably I've introduced a small bug in the latest one.

**Comment by elfman** [comment]
@birdofpreyru I removed the folder 'node_modules/' and run `npm install` to install again, it could work now, I don't know why. Sorry for wasting your time.
