### ISSUE TITLE
[$40] Settings > Account > My Account: Entering incorrect current password to change the password won't show any validation

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2056]
![image](https://user-images.githubusercontent.com/42398485/54463132-0b070800-4740-11e9-9bf3-2e8dff14f531.png)

1. Open the application and login as Manager (pshah_manager)
2. Hover over the profile avatar > Click Settings
3. Click Account Tab > My Account
4. Enter 'qwert123@' to the new password field
5. Enter '123456' as Current password
6. Click Change Password

**Actual:** Entering incorrect current password to change the password won't show any validation

**Expected:** Should show a validation because the current password entered into the field is incorrect

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30086772 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30086772 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by RAJKUMARRRR** [comment]
i want to work on this issue, can you change the label

**Comment by ThomasKranitsas** [comment]
@RAJKUMARRRR please use this link https://x.topcoder.com/api/v1/github/teams/registration/7946e40e-f01a-4ced-a1c2-081e328c7d73-1553097709824 to access our org so you can assign yourself

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30086772 has been updated - it has been assigned to LieutenantRoger.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by LieutenantRoger** [comment]
Hey @ThomasKranitsas , 

So when the password is incorrect, how do we notify the user ?

**Comment by ThomasKranitsas** [comment]
Hey @LieutenantRoger ,

Please show an error like the one from the following screenshot:
<img width="881" alt="Screenshot 2019-03-21 at 10 06 40" src="https://user-images.githubusercontent.com/4612921/54743153-11780280-4bcc-11e9-87a4-febf9b3c0905.png">

**Comment by LieutenantRoger** [comment]
[https://take.ms/skp6M](url)

Can we show a tip like this ? To match the popup with the email invalid state on this same screen ?

**Comment by ThomasKranitsas** [comment]
No, please use the one I shared above

**Comment by LieutenantRoger** [comment]
Ok,  https://take.ms/XL8WY  does this style look good to you ? I picked an existing one.

And this is only for client side validation, we won't check with backend about whether current password correct or wrong, right ? Because invalid only indicates a format error.

**Comment by ThomasKranitsas** [comment]
I think there's a misunderstanding here... This error is shown when you submit the form and the backend returns an error.

It's not a form validation error, it's a bad request error

**Comment by LieutenantRoger** [comment]
Hey @ThomasKranitsas,  I have read the backend codebase, it looks like the topcoder-react-lib didn't handle the error case when updating failed. 

Can we use `fireErrorMessage('The old password is invalid');` to notify user about the fail ?   As I can see there are other errors in the topcoder-react-lib is using this way to alert error. 

The way you showed above actually was a client validation style. 

Let me know your thoughts.

**Comment by ThomasKranitsas** [comment]
That sounds good

**Comment by LieutenantRoger** [comment]
ok, do I create a pull request on topcoder-react-lib master branch?  I didn't find a bug-bash branch on that codebase.

**Comment by ThomasKranitsas** [comment]
Please use the develop branch

**Comment by LieutenantRoger** [comment]
When I modify the topcoder-react-lib in the node_module, and re-build the community-app, do you know why the bundled topcoder-react-lib is not containing my update to the topcoder-react-lib ?

**Comment by ThomasKranitsas** [comment]
You also need to build the topcoder-react-lib before you replace it in the community-app

**Comment by LieutenantRoger** [comment]
factory:45ms building:314ms = 359ms

ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: [BABEL] /Users/Roger/w/bb/tc/topcoder-react-lib/src/index.js: Unknown option: base.envName. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options.
    at Logger.error (/Users/Roger/w/bb/tc/topcoder-react-lib/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/Roger/w/bb/tc/topcoder-react-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
    at OptionManager.init (/Users/Roger/w/bb/tc/topcoder-react-lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/Roger/w/bb/tc/topcoder-react-lib/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/Roger/w/bb/tc/topcoder-react-lib/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/Roger/w/bb/tc/topcoder-react-lib/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/Roger/w/bb/tc/topcoder-react-lib/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/Roger/w/bb/tc/topcoder-react-lib/node_modules/babel-loader/lib/index.js:173:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! topcoder-react-lib@0.7.8 build:dev: `webpack --env=development --progress --profile --colors --display-optimization-bailout`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the topcoder-react-lib@0.7.8 build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Roger/.npm/_logs/2019-03-21T16_07_08_072Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! topcoder-react-lib@0.7.8 build: `npm run clean && npm run build:dev && npm run build:prod`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the topcoder-react-lib@0.7.8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Roger/.npm/_logs/2019-03-21T16_07_08_106Z-debug.log


I can't build topcoder-react-lib both develop and master branch, can you see the issue ?

**Comment by LieutenantRoger** [comment]
@ThomasKranitsas   
Please check this PR against topcoder-react-lib
Thanks.  
https://github.com/topcoder-platform/topcoder-react-lib/pull/48

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30086772<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```
