### ISSUE TITLE
[$50]Challenge Specification : Style issues

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4510]
The styles on the challenge spec do not match with V4.
https://beta-community-app.topcoder.com/challenges/9598b9b7-7a6d-4c82-ad04-9e60435ffe88
https://www.topcoder.com/challenges/30127483

<img width="1440" alt="Screenshot 2020-06-10 at 10 56 28 AM" src="https://user-images.githubusercontent.com/58783823/84230224-1eeb1680-ab09-11ea-830c-f66f129ab380.png">
<img width="1440" alt="Screenshot 2020-06-10 at 10 56 51 AM" src="https://user-images.githubusercontent.com/58783823/84230238-25798e00-ab09-11ea-898b-b3a9b6618e0a.png">

**Comment by SathyaJayabal** [comment]
@sushilshinde @lakshmiathreya @Oanh-and-only-Oanh 
This includes missing links too. 
For example:
https://beta-community-app.topcoder.com/challenges/8f0a48fc-e7f5-4ff6-acfa-bcf1b30f304d
https://www.topcoder.com/challenges/30135380
<img width="1440" alt="Screenshot 2020-08-10 at 3 06 33 PM" src="https://user-images.githubusercontent.com/58783823/89769699-394a6c00-db1b-11ea-9abb-8618da2f8f31.png">

**Comment by crazyk07** [comment]
Contest https://www.topcoder.com/challenges/30137528 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by sushilshinde** [comment]
@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

Submit in 8 hours and PR to

https://github.com/topcoder-platform/community-app/tree/integration-v5-challenge-api
https://github.com/topcoder-platform/topcoder-react-lib/tree/integration-v5-challenge-api

run `npm run test` before PR

**Comment by mfikria** [comment]
@sushilshinde @crazyk07 can i work on this?

**Comment by fikzzzy** [comment]
@sushilshinde @crazyk07 can i work on this?

**Comment by crazyk07** [comment]
[500]: Failed to get topcoder member id.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment]
[500]: Failed to get topcoder member id.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by Oanh-and-only-Oanh** [comment]
@fikzzzy, go ahead and work on it and we'll figure out what's going on with the "Failed message".

**Comment by sushilshinde** [comment]
Thanks, some technicical problem with the staging environemnts PR so not merged.

**Comment by sushilshinde** [comment]
Thanks, some technicical problem with the staging environemnts PR so not merged.

**Comment by sushilshinde** [comment]
@fikzzzy I see this error 


```
ERROR in ./src/shared/components/challenge-detail/Specification/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: /opt/app/src/shared/components/challenge-detail/Specification/index.jsx: Could not resolve the styleName 'h2'.
    at styleNameValue.split.filter.map.styleName (/opt/app/node_modules/babel-plugin-react-css-modules/dist/getClassName.js:83:15)
    at Array.map (<anonymous>)
    at exports.default (/opt/app/node_modules/babel-plugin-react-css-modules/dist/getClassName.js:66:6)
    at exports.default (/opt/app/node_modules/babel-plugin-react-css-modules/dist/resolveStringLiteral.js:23:56)
    at PluginPass.JSXElement (/opt/app/node_modules/babel-plugin-react-css-modules/dist/index.js:193:48)
    at newFn (/opt/app/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/opt/app/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/opt/app/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/opt/app/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/opt/app/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/opt/app/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/opt/app/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/opt/app/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/opt/app/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/opt/app/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/opt/app/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/opt/app/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/opt/app/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/opt/app/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/opt/app/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/opt/app/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/opt/app/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/opt/app/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/opt/app/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/opt/app/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/opt/app/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/opt/app/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/opt/app/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/opt/app/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/opt/app/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/opt/app/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/opt/app/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/opt/app/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/opt/app/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/opt/app/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/opt/app/node_modules/babel-traverse/lib/context.js:108:19)
 @ ./src/shared/containers/challenge-detail/index.jsx 81:21-79
 @ ./src/shared/routes/ChallengeDetails.jsx
 @ ./src/shared/routes/Topcoder/Routes.jsx
 @ ./src/shared/routes/Topcoder/index.jsx
 @ ./src/shared/routes/index.jsx
 @ ./src/shared/app.jsx
 @ ./src/shared/index.jsx
 @ ./src/client/index.jsx
```

**Comment by fikzzzy** [comment]
@sushilshinde fixed in https://github.com/topcoder-platform/community-app/pull/4790

**Comment by lakshmiathreya** [comment]
<img width="1428" alt="Screenshot 2020-08-20 at 5 03 27 PM" src="https://user-images.githubusercontent.com/51733042/90765746-17659c00-e308-11ea-9c1b-83360e3ded6c.png">
<img width="1390" alt="Screenshot 2020-08-20 at 5 03 41 PM" src="https://user-images.githubusercontent.com/51733042/90765759-1c2a5000-e308-11ea-9a57-edbed60fbd05.png">
<img width="1408" alt="Screenshot 2020-08-20 at 5 09 27 PM" src="https://user-images.githubusercontent.com/51733042/90765764-1e8caa00-e308-11ea-949f-ecea21a15b68.png">

**Comment by SathyaJayabal** [comment]
Only a few of the style issues are fixed. We still see many styles not rendered properly.

example:
Bold / Italics etc
(v4) https://beta-community-app.topcoder.com/challenges/30129332
(V5) https://staging-community-app.topcoder.com/challenges/118cb7f0-25e9-40e5-83ee-bd6fb3514e1d
<img width="1440" alt="Screenshot 2020-08-24 at 12 46 37 PM" src="https://user-images.githubusercontent.com/58783823/91015296-8c86e900-e608-11ea-97e8-2779ce173ff3.png">

Lists in some cases
(V4)https://beta-community-app.topcoder.com/challenges/30137850
(V5)https://staging-community-app.topcoder.com/challenges/c74d6aa8-0724-40a5-b177-3bf05b36e046
<img width="1440" alt="Screenshot 2020-08-24 at 12 50 14 PM" src="https://user-images.githubusercontent.com/58783823/91015277-85f87180-e608-11ea-8797-9aad7750235f.png">
<img width="1440" alt="Screenshot 2020-08-24 at 12 50 34 PM" src="https://user-images.githubusercontent.com/58783823/91015298-8c86e900-e608-11ea-877a-e7a38fe4c2cf.png">

**Comment by fikzzzy** [comment]
@sushilshinde add missing styles in https://github.com/topcoder-platform/community-app/pull/4805

**Comment by SathyaJayabal** [comment]
@fikzzzy , we will handle the rest of the style issues in #4802

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-08-24 at 8 52 58 PM" src="https://user-images.githubusercontent.com/58783823/91063585-d34a0280-e64b-11ea-8697-b78a3304a9a0.png">

**Comment by crazyk07** [comment]
Payment failed: [500]: Failed to get topcoder member id.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment]
[500]: Failed to get topcoder member id.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment]
Payment failed: [500]: Failed to get topcoder member id.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by sushilshinde** [comment]
@fikzzzy please wait for payment some problem with the system

**Comment by crazyk07** [comment]
Payment failed: [500]: Failed to get topcoder member id.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment]
Payment failed: [500]: Failed to get topcoder member id.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by rootelement** [comment]
@fikzzzy what is your Topcoder handle?

**Comment by fikzzzy** [comment]
> @fikzzzy what is your Topcoder handle?

fikzzzy

**Comment by crazyk07** [comment]
Payment failed: [500]: Failed to get topcoder member id.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment]
Contest https://www.topcoder.com/challenges/30137528 has been updated - mfikria has been unassigned.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment]
Payment failed: [500]: Failed to get topcoder member id.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment]
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by rootelement** [comment]
I'm not sure what is up with this issue. Going to pay it out via a direct payment. Closing this out.

**Comment by crazyk07** [comment]
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by Oanh-and-only-Oanh** [comment]
@fikzzzy, payment was paid via TASK for this ticket to you. https://www.topcoder.com/direct/contest/detail?projectId=30140347
