### ISSUE TITLE
[$40] Automated Smoke Testing Fix Test Case TC_020 and TC_021

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5458]
**Before Login Test Cases [TC-020] should verify that when user selects a challenge "tag", only challenges under the selected tag are shown**

- Challenge Tag changed from to in Challenge Details page

```
Error: Failed expectation
        at Function.<anonymous> (/automated-smoke-test/page-objects/pages/topcoder/challenge-listing/challenge-listing.helper.ts:595:46)
        at step (/automated-smoke-test/temp/page-objects/pages/topcoder/challenge-listing/challenge-listing.helper.js:33:23)
        at Object.next (/automated-smoke-test/temp/page-objects/pages/topcoder/challenge-listing/challenge-listing.helper.js:14:53)
        at fulfilled (/automated-smoke-test/temp/page-objects/pages/topcoder/challenge-listing/challenge-listing.helper.js:5:58)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

Send PR to branch **circleci-automation-testing**

**Comment by luizrrodrigues** [comment]
Challenge https://www.topcoder.com/challenges/91a1cf63-61e0-4188-b56f-a00aed21a992 has been created for this ticket.<br/><br/>```This is an automated message for luizrrodrigues via Topcoder X```

**Comment by luizrrodrigues** [comment]
Challenge https://www.topcoder.com/challenges/91a1cf63-61e0-4188-b56f-a00aed21a992 has been assigned to nursoltan-s.<br/><br/>```This is an automated message for luizrrodrigues via Topcoder X```

**Comment by nursoltan-s** [comment]
PR: https://github.com/topcoder-platform/community-app/pull/5465

**Comment by SathyaJayabal** [comment]
verified on staging

https://app.circleci.com/pipelines/github/topcoder-platform/community-app/2949/workflows/1f4bb6db-5e17-495e-8d02-28af3bca84c3/jobs/12671

**Comment by SathyaJayabal** [comment]
verified on prod
https://app.circleci.com/pipelines/github/topcoder-platform/community-app/2953/workflows/9824d1b1-d7bd-4ae2-83a2-9ce1a02e0320/jobs/12676

**Comment by luizrrodrigues** [comment]
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for luizrrodrigues via Topcoder X```

**Comment by luizrrodrigues** [comment]
Challenge https://www.topcoder.com/challenges/78a7d287-90a5-4f08-962a-a086459d200e has been created for this ticket.<br/><br/>```This is an automated message for luizrrodrigues via Topcoder X```

**Comment by luizrrodrigues** [comment]
Payment task has been updated: https://www.topcoder.com/challenges/78a7d287-90a5-4f08-962a-a086459d200e
*Payments Complete*
Winner: nursoltan-s
Copilot: luizrrodrigues
Challenge `78a7d287-90a5-4f08-962a-a086459d200e` has been paid and closed.<br/><br/>```This is an automated message for luizrrodrigues via Topcoder X```
