### ISSUE TITLE
Payments App: not closing payments.

### ISSUE THREAD

**Issue by kbowerma** [topcoder-platform/community-app#570]
When using the payment app,  it does not finish closing the payment.   Gets stuck on this view

![image](https://user-images.githubusercontent.com/1180747/32506588-8ca711cc-c3aa-11e7-90b7-74e56daf6c57.png)

and throws the following error:

chunk.js:6 Uncaught (in promise) Error
    at e.<anonymous> (http://community-app.topcoder.com/community-app-assets/sandbox-payment/chunk.js:6:123482)
    at r (http://community-app.topcoder.com/community-app-assets/main.js:26:84536)
    at Generator._invoke (http://community-app.topcoder.com/community-app-assets/main.js:26:85581)
    at Generator.e.(anonymous function) [as next] (http://community-app.topcoder.com/community-app-assets/main.js:26:84715)
    at r (http://community-app.topcoder.com/community-app-assets/main.js:6:122544)
    at http://community-app.topcoder.com/community-app-assets/main.js:6:122640
    at <anonymous>

**Comment by rootelement** [comment]
I have the same issue. It hangs on that screen, then I have to flip over to direct, hit the close button, and select a winner.

**Comment by cwdcwd** [comment]
@kbowerma @rootelement will get this one in queue. Does this happen every time? Any steps for reproduction I should be aware of?

**Comment by rootelement** [comment]
It's happened every time I've used the task app in the past, say, 3 weeks. Very simple steps to reproduce... Fill out the form, click submit. It creates the challenge, assigns the member, but when it gets to the step in the screenshot above, it just hangs there. If you close out of the task app and go to the challenge in direct, the challenge is there, but in the state where you have to click the close button and select the winner.

**Comment by cwdcwd** [comment]
@kbowerma @rootelement pls retest

**Comment by rootelement** [comment]
Worked perfect for me, Thanks!
