### ISSUE TITLE
Webpack issue when building

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6384]
**Describe the bug**
I'm running into what appears to be a web pack issue when attempting to build the community app locally on macOS.  I'm using node `8.2.1`.

**To Reproduce**

1. `npm i`
2. `npm run dev`
3. See error

**Expected behavior**
App runs locally

**Log**

```
v8.2.1 ❯ npm run dev

> community-app@1.0.0 dev /Volumes/External/Git/community-app
> cross-env BABEL_ENV=development NODE_ENV=development node ./bin/www

Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.
/Volumes/External/Git/community-app/node_modules/joi/lib/ref.js:80
    return exports.create(key, { ...options, in: true });
                                 ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/External/Git/community-app/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! community-app@1.0.0 dev: `cross-env BABEL_ENV=development NODE_ENV=development node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the community-app@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/justingasper/.npm/_logs/2022-06-14T00_03_57_485Z-debug.log
```

**Desktop (please complete the following information):**
<img width="698" alt="Screen Shot 2022-06-14 at 10 05 27 am" src="https://user-images.githubusercontent.com/21790/173466719-56626851-bd50-4480-a656-78f1870d09f8.png">

**Comment by kkartunov** [comment]
Hey @jmgasper,

from looking at your dump, it looks you have env issues you need to resolve.
- try use the exact node version as in the .nvmrc file. You could do `nvm use` or handle yourself
- you will need to set evn vars for local deployment

The community-app runs locally without issues for me and other developers. Thus I will label this as `Not an App issue`.

**Comment by jmgasper** [comment]
1.  I was going off the README, which states node 8.2.1.  I think the README should be updated if that's not correct.  I'll retry with 8.11.2
2. Again, are those ENV variables documented in the README?  Which ones should I be setting?  I set NODE_CONFIG_ENV to `development`.

**Comment by jmgasper** [comment]
Just for background - I'm working on clearly documenting the steps to get this running for devs on Windows, Linux, and Mac, so I'm double checking all our documentation to make sure it's current.  I'm going to remove mentions of versions so that the documentation doesn't go stale again.

**Comment by kkartunov** [comment]
Hey @jmgasper,

before you start, you should access /etc/hosts and add the line 127.0.0.1 local.topcoder-dev.com.

then try this:
1. npm i
2. npm run buiild
3. set ENV vars
4. npm run dev
