### ISSUE TITLE
css does not build due to missing node-sass/vendor directory

### ISSUE THREAD

**Issue by kondakovdmitry** [topcoder-platform/community-app#718]
When running `npm run build` I get lots of errors like the following: 
```
ERROR in ./node_modules/css-loader?{"importLoaders":3,"localIdentName":"[hash:base64:6]","modules":true}!./node_modules/postcss-loader/lib?{"plugins":[null]}!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./src/shared/components/tc-communities/communities/blockchain/Learn/Tutorials/style.scss
    Module build failed: Error: ENOENT: no such file or directory, scandir 'c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\node-sass\vendor'
        at Object.fs.readdirSync (fs.js:904:18)
        at Object.getInstalledBinaries (c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\node-sass\lib\extensions.js:128:13)
        at foundBinariesList (c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\node-sass\lib\errors.js:20:15)
        at foundBinaries (c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\node-sass\lib\errors.js:15:5)
        at Object.module.exports.missingBinary (c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\node-sass\lib\errors.js:45:5)
        at module.exports (c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\node-sass\lib\binding.js:15:30)
        at Object.<anonymous> (c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\node-sass\lib\index.js:14:35)
        at Module._compile (module.js:635:30)
        at Object.Module._extensions..js (module.js:646:10)
        at Module.load (module.js:554:32)
        at tryModuleLoad (module.js:497:12)
        at Function.Module._load (module.js:489:3)
        at Module.require (module.js:579:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\sass-loader\lib\loader.js:3:14)
        at Module._compile (module.js:635:30)
        at Object.Module._extensions..js (module.js:646:10)
        at Module.load (module.js:554:32)
        at tryModuleLoad (module.js:497:12)
        at Function.Module._load (module.js:489:3)
        at Module.require (module.js:579:17)
        at require (internal/module.js:11:18)
        at loadLoader (c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at iteratePitchingLoaders (c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
        at c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\loader-runner\lib\LoaderRunner.js:173:18
        at loadLoader (c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\loader-runner\lib\loadLoader.js:36:3)
        at iteratePitchingLoaders (c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at iteratePitchingLoaders (c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
        at c:\Works\_TopCoder\30061839 Community App - Bug Bash 2\community-app\node_modules\loader-runner\lib\LoaderRunner.js:173:18
```
node versoin: v8.9.3
npm version: 5.5.1

**Comment by kondakovdmitry** [comment]
Deleting `node_modules` dir and running `npm install` again resolved this issue.

It was caused by missing Python 2.7 during first installation of the app with `npm install`. So the steps to reproduce the issue are:
1. Run `npm install` with Python 2.7 NOT installed. The installation will fail because Python 2.7 is required by the node-gyp build (note, that Python 3.6 is not supported by node-gyp).
2. Install Python 2.7.
3. Run `npm install` again. The installation will succeed, but node-sass/vendor will not be downloaded in this case. This will lead to app build errors and missing css stylesheets in the app.
